#include "clear_net.h"
#include "autodiff.h"
#include "data.h"
#include "net.h"

#define PAIR(func) .func = func

_cn_names const cn = {
    .ad =
        {
            PAIR(allocCompGraph),
            PAIR(deallocCompGraph),
            PAIR(initLeafScalar),
            PAIR(getVal),
            PAIR(getGrad),
            PAIR(applyGrad),
            PAIR(add),
            PAIR(sub),
            PAIR(mul),
            PAIR(raise),
            PAIR(relu),
            PAIR(leakyRelu),
            PAIR(htan),
            PAIR(sigmoid),
            PAIR(elu),
            PAIR(backward),
            PAIR(setValRand),
        },
    .data =
        {
            PAIR(deallocMatrix),
            PAIR(allocMatrix),
            PAIR(formMatrix),
            PAIR(printMatrix),
            PAIR(allocVector),
            PAIR(formVector),
            PAIR(printVector),
            PAIR(deallocVector),
            PAIR(shuffleDatas),
            PAIR(setBatchFromMatrix),
            PAIR(allocDataFromVectors),
            PAIR(allocDataFromMatrices),
            PAIR(allocDataFromMultiChannelMatrices),
            PAIR(deallocData),
            PAIR(allocVectors),
            PAIR(allocMatrices),
            PAIR(allocMultiMatrices),
            PAIR(deallocVectors),
            PAIR(deallocMatrices),
            PAIR(deallocMultiMatrices),
            PAIR(printVectors),
            PAIR(printMatrices),
            PAIR(printMultiMatrices),
            PAIR(printData),
            PAIR(setBatch),
            PAIR(allocEmptyData),
        },
    PAIR(allocDefaultHParams),
    PAIR(setRate),
    PAIR(setLeaker),
    PAIR(withMomentum),
    PAIR(allocConvNet),
    PAIR(allocVanillaNet),
    PAIR(allocDenseLayer),
    PAIR(randomizeNet),
    PAIR(deallocNet),
    PAIR(printNet),
    PAIR(predictVanilla),
    PAIR(printVanillaPredictions),
    PAIR(predictConvToVector),
    PAIR(predictConvToMatrix),
    PAIR(printConvPredictions),
    PAIR(lossVanilla),
    PAIR(backprop),
    PAIR(saveNet),
    PAIR(allocNetFromFile),
    PAIR(allocConvLayer),
    PAIR(allocPoolingLayer),
    PAIR(allocGlobalPoolingLayer),
    PAIR(lossConv),
};
